### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by HFG43** [ahmedeid6842/Leaderboard#3]
Hi Ahmed! @Alibaba2023 and I will like to say that your project looks great! Very clean code, and very easy to understand the flow.

We kindly suggest that in fetching.js put your fetch code inside the `try` and `catch` statements to avoid sever side errors.

Happy coding! 😎😎

**Comment by ahmedeid6842** [comment]
Applied the try-catch suggestion :gear:, please review the updated code.
Thanks again for you review :pray:
